version: "3.7"
services:
  redis:
    image: redis:latest

  dev:
    command: python3.10 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

    build:
      context: .
      target: zeus_dev
    volumes:
      - .:/home/user/zeus:rw
    working_dir: /home/user/zeus
    environment:
      - PGHOST=postgres
      - PGDATABASE=zeus
      - PGUSER=zeus
      - PGPASSWORD=password
      - ZEUS_PROD_HOST=localhost:8000
      - ZEUS_PROD_USE_HTTPS=False
      - ZEUS_DEPLOYMENT=dev
      - DJANGO_SETTINGS_MODULE=settings.dev
    depends_on:
      - redis
      - postgres

  dev_celery:
    command: celery -A zeus.celery worker -l INFO --concurrency 1 --pool solo

    build:
      context: .
      target: zeus_dev
    volumes:
      - .:/home/user/zeus:rw
    working_dir: /home/user/zeus
    environment:
      - PGHOST=postgres
      - PGDATABASE=zeus
      - PGUSER=zeus
      - PGPASSWORD=password
      - DJANGO_SETTINGS_MODULE=settings.dev
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: zeus
      POSTGRES_DB: zeus
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
